<div class="field required">
    <label for="popup-mobile" class="label"><span><?php /* @escapeNotVerified */ echo __('Mobile Number') ?></span></label>
    <div class="control">
        <input type="tel" name="customer_mobile_number" id="create-customer-phone" value="" title="<?php /* @escapeNotVerified */ echo __('Customer Mobile Number') ?>" class="validate-length minimum-length-10 input-text" data-validate="{required:true}">
        <div class="field note"><?php /* @escapeNotVerified */ echo __('Enter Mobile With Country Code.') ?></div>
    </div>
</div>
<?php
$rgisterBlock = $this->getLayout()->createBlock('DarshilTech\SmsNotification\Block\Form\Register');
?>
<script type="application/javascript">
    require([
        'jquery',
        'intlTelInput'
    ], function($) {
        $("#create-customer-phone").intlTelInput(<?php echo $rgisterBlock->getPhoneconfig(); ?>)

    });
</script>